### PR TITLE
Changed Cappuccino.doxygen EXCLUDE_PATTERNS to exclude nothing.

### LINKED ISSUE #1956: 0.9.7_alpha1 documentation incomplete
Classes such as CPArray are no longer shown in the generated documentation.

Upon investigation, all files with leading underscores are ignored.
All symbols with leading underscores are ignored.

The current CPArray is located in _CPArray.j (leading underscore), and the implementation is based upon a class with a leading underscore.

### PR DESCRIPTION
**Pull request by theredhead**
Changed glob pattern from _* to <empty> for the EXCLUDE_PATTERNS
configuration field in the doxygen configuration file.

This should fix #1956

### CODE REVIEW

**Comment by daboe01** [comment]
-#new
milestone=1.0
Documentation
+#needs-review

**Comment by theredhead** [comment]
This is not enough. there are other places where underscore prefixed filenames are specifically excluded during the documentation build process. I'm doing more research.

**Comment by daboe01** [comment]
+#needs-improvement

**Comment by mrcarlberg** [comment]
@theredhead How can we move this PR forward?

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
