### PR TITLE
New: bindings support for CPTextView + dragging improvements

### LINKED ISSUE #2523: CPTextView does not support bindings
+TextView

### PR DESCRIPTION
**Pull request by daboe01**
previously, bindings did not work for CPTextView

this PR adds basic support for value and attributedString
this PR also updates the manual test ContinuouslyUpdatesValueBinding with a textview to make the the new functionality testable

fixes #2523

### CODE REVIEW

**Comment by daboe01** [comment]
-#new
+#needs-review
+bindings
+TextView

**Comment by theredhead** [comment]
My initial CPTextView binding test now behaves more or less as expected, however (this could be completely unrelated), the first time I type into a textview bound to an attributed string on the app controller, its textcolor is a lightish gray. when I then click out of it (in another textview bound to a normal CPString), type a few characters there and click back into the CPTextView that is bound to the attributed string, its textcolor has become the normal black.

In my text this looks like this:

gray-to-black

**Comment by daboe01** [comment]
@theredhead i _think_ i have fixed the lightish gray issue. could you please try again?

**Comment by daboe01** [comment]
@theredhead thank you. looks like the grey from a placeholder is somehow copied over to the typingattributes (this is exactly what i tried to prevent with commit 1f560c92fc6e015b8f26512ced22a83e79848373). could you please post the project from the sceencast, so i can have a look with the debugger?

**Comment by theredhead** [comment]
@daboe01 that project is attached in the second zipfile with my previous comment.

**Comment by daboe01** [comment]
@theredhead thank you! should be fixed by ace1332

**Comment by theredhead** [comment]
@daboe01 indeed that does, thank you!

**Comment by daboe01** [comment]
@mrcarlberg may you have a look when time permits :-)

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
