### PR TITLE
Aristo3: various _CPImageAndTextView bugs

### PR DESCRIPTION
**Pull request by didierkorthoudt**
Minors fixes / enhancements :
- typo
- `CPImageScaleProportionallyUpOrDown`  is now active

### CODE REVIEW

**Comment by didierkorthoudt** [comment]
@cacaodev Could you please specify which kind of tests you're waiting for ?

**Comment by cacaodev** [comment]
I am waiting for a Manual test for the imageScaling feature of _CPImageAndTextView or a reference to such test if it already exists in the repo.

**Comment by didierkorthoudt** [comment]
@cacaodev I've added a manual test that shows the effect of this PR on the imageScaling feature.

Before this PR : 
Bad4

After this PR : 
Good4

**Comment by mrcarlberg** [comment]
@cacaodev Do you think we can merge this now?

**Comment by cacaodev** [comment]
Looks good to me. There is still a pre-existing general issue for all modes except "axes independently" where the image is not centered after transformation. If you have some time to work on this you can do it here, otherwise I will commit the pr and open a new issue.

**Comment by didierkorthoudt** [comment]
@cacaodev I'll have a look at this…

**Comment by didierkorthoudt** [comment]
@mrcarlberg Please wait on this one…

**Comment by mrcarlberg** [comment]
@didierkorthoudt Is this one ready now?

**Comment by didierkorthoudt** [comment]
@mrcarlberg Well, I'll try to implement @cacaodev suggestion. Please hold on this one for now.

**Comment by didierkorthoudt** [comment]
@mrcarlberg @cacaodev The centering stuff also impacts CPImageView so I suggest to deal with it in another PR. So this one is done.

**Comment by daboe01** [comment]
-#new
+Theme

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
