### PR TITLE
FIXED: This PR adapts views and custom views decoding to fix "not ready view" bugs.

### PR DESCRIPTION
**Pull request by didierkorthoudt**
This is a (working) attempt to fix those issues.

### CODE REVIEW

**Comment by didierkorthoudt** [comment]
+FIFO

**Comment by mrcarlberg** [comment]
I guess the problem that is being fixed here is the good old problem we have had for many many years? The question is if this is a final solution for this problem or is it as every earlier fixes just a partly fix? That means that someone else will have a nib file that will not work with this solution of the problem?

**Comment by didierkorthoudt** [comment]
Well, indeed this is not a structural solution, this is just a fix on the current system. It works with all my tests but I can't say it resolves all potential problems. This was constructed by observing things at runtime.

A more global approach would be to rewrite the whole CIB loading system and, in fact, I think we could completely bypass the XIB conversion and load directly the XIB and interpret it. This would make Cappuccino more close to Cocoa than today.

I've noted this on my (looooong) list of things to think of after Aristo3…

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
