### PR TITLE
fixed: CPSearchField's bezel did not resize

### LINKED ISSUE #2986: CPSearchField's bezel does not resize properly
this is introduced by 5c4107835b415e11008e26d1614d2920de561ad1

you can see it by means of making a search field horizontally resizable.

### PR DESCRIPTION
**Pull request by daboe01**
fixes #2986

### CODE REVIEW

**Comment by daboe01** [comment]
+theme

**Comment by daboe01** [comment]
@didierkorthoudt can you have a look, please?

**Comment by daboe01** [comment]
-#new
+theme

**Comment by didierkorthoudt** [comment]
Hi @daboe01,

Your fix is correct.
My bad, the test on !_contentView was not correctly positioned.
I've pushed an optional fix (only for performances).
Are you OK with this ?

**Comment by daboe01** [comment]
@didierkorthoudt yes. you are the boss ;-)

**Comment by daboe01** [comment]
+#ready-to-commit

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
