### PR TITLE
Update XcodeCapp copyright notice in 'About' window

### PR DESCRIPTION
**Pull request by enquora**
* Use copyright string from Info.plist
    (was previously hard-coded in About window, despite also being set in Info.plist).
* Create copyright property on AppDelegate.
* Append 'All rights reserved' in code, remove from Info.plist value
    (make line breaking in About window easier to manage, ease localization, ease automated checking of copyright dates.)
* Display copyright notice using bindings.
* Resize copyright field to prevent truncated text.
* Set resize masks for all window fields - not currently set.
* Resize window to golden ratio for improved visual presentation.

### CODE REVIEW

**Comment by cacaodev** [comment]
@enquora I'm sorry but it seems we've created some conflicts with this pr. Can you resolve them, otherwise it seems good to me. Thank you for this.

**Comment by enquora** [comment]
I may well have implemented this prior to the full merge of 1.0. Will clean it up — nothing dramatic is changed.

**Comment by daboe01** [comment]
-#new
+#needs-improvement

**Comment by mrcarlberg** [comment]
@enquora Can you fix the conflicts on this pull request so it can be merged? Also the test cases fails for some reason.

**Comment by enquora** [comment]
@mrcarlberg Someone posted a link to dark mode support several weeks ago in Gitter. This should probably be fixed simultaneously with that but I'm having trouble locating it in the Gitter history and don't see a pull request. You don't remember roughly when that was, do you?

**Comment by daboe01** [comment]
@enquora can you please update this one by re-running nib2cib? this should fix the merge-conflict.

**Comment by daboe01** [comment]
@enquora is this PR possibly obsoleted with your recent work on XcodeCapp?

**Comment by enquora** [comment]
It's intended to keep this separate from the major work on XcodeCapp.
This PR is being used as a sort of bookmark for myself while my local CappuccinoSource is cleaned up to reflect the promotion of Node to default.

I would like to keep this open for another week or two while this and a few other items are prepped for (re)submitting.

**Comment by enquora** [comment]
Replaced with new commits to 'main' branch only.

**Pull request closed without merging**
