### PR TITLE
Compile without gcc [+2]

### PR DESCRIPTION
**Pull request by mrcarlberg**
Removed the use of the gcc (or clang on Mac OS X) preprocessor. We can now compile the Cappuccino frameworks on a pure Javascript system. It is also around 50% faster to compile as most of the time was spent launching gcc in a separate process for each compiled file.

Also added support for Javascript Source Maps. This will allow us in the future to show the Objective-J source file in the debugger when stepping thru code.

### CODE REVIEW

**Comment by kerusan** [comment]
Yeah! Wow.

--kerusan

Skickat från min iPad

**Comment by Dogild** [comment]
This is awesome! Good job!

**Comment by langovoi** [comment]
Well done!

**Comment by daboe01** [comment]
+1

**Comment by langovoi** [comment]
+1

**Comment by mrcarlberg** [comment]
We need help to test this. It is very easy to do:
1. Just checkout this version.
2. Build the new version of Cappuccino.
3. If needed copy the Cappuccino frameworks to your project.
4. Run and test your project.

Here is a more hands on way to do it:
1. ```cd <path to put temporary repository>```
2. ```git clone https://github.com/mrcarlberg/cappuccino.git```
3. ```cd cappuccino```
4. ```git checkout compile_without_gcc```
5. ```jake clobber```
6. ```jake install```
7. ```cd <your project path>```
8. ```capp gen -f .``` or copy the ```Objective-J```, ```Foundation``` and ```AppKit``` frameworks from the ```<build>``` folder to your project.
9. Test you app.

**Comment by daboe01** [comment]
build time: 1 minute (down from 1:47).
exellent job!
i am not seeing any issues with one of my more complex apps after an hour of heavy testing: https://github.com/daboe01/Clinical

**Comment by michaelbach** [comment]
It surprised me that the build appears in my usual cappuccino directory, not in <path to put temporary repository>. But I confirm (on a touchbar-MacBook pro): build time is now halved, down to 00:01:03, was 00:02:08 here.
And I have no issues with my (to date) largest Cappuccino program.
Fabulous! Thanks! 
In awe, best, Michael

**Comment by mrcarlberg** [comment]
@daboe01 Great feedback. Thanks for testing!

**Comment by mrcarlberg** [comment]
@michaelbach It should not be any different where the build is placed. Can you please check again with the master branch and compare.

**Comment by mrcarlberg** [comment]
@michaelbach Ok, I didn't see that you updated your comment. Great! Thanks for testing!

**Comment by michaelbach** [comment]
Dear Martin:

> @michaelbach Ok, I didn't see that you updated your comment. Great! Thanks for testing!
Thank YOU for developing this, and more.

Best, Michael
-- 
Prof. Michael Bach PhD, Eye Center, University of Freiburg, Killianstr. 5, 79106 Freiburg, Germany. 
Michael.Bach@uni-freiburg.de   <http://michaelbach.de>

**Comment by mrcarlberg** [comment]
Merged!

**Pull request merged**
