### PR TITLE
FIXED: CPButtonBar actionPopupButton was incorrectly displayed

### LINKED ISSUE #2770: Image of an actionPopupButton in CPButtonBar does not appear
When I compile the latest master, the image of the actionPopupButton in a CPButtonBar does not appear anymore.

image

### PR DESCRIPTION
**Pull request by didierkorthoudt**
The actionPopupButton was setting a special content-inset value using `[button setValue:CGInsetMake(0, 0, 0, 0) forThemeAttribute:"content-inset »`, thus for the CPThemeStateNormal, but the actionPopupButton sets the CPPopUpButtonStatePullsDown theme state. So the theme value defined for this theme state in the theme descriptors (0, 32, 0, 5) was not overridden and leads to displaying the button image outside the visible rect.

This PR simply specify the CPPopUpButtonStatePullsDown in the setValue:forThemeAttribute method.

Fixes #2770.

### CODE REVIEW

**Comment by jasperdeb** [comment]
The fix seems to work

**Comment by didierkorthoudt** [comment]
If you see something strange elsewhere, please don't hesitate to ask me on Gitter ! It's a deep change and some other side effects may remain. Thank you for your time !

**Comment by jasperdeb** [comment]
If I see something, I will pose a new issue.

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
