### PR TITLE
fixed: CoreGraphics does not have basic text drawing support

### PR DESCRIPTION
**Pull request by daboe01**
previously, drawing text on a view was next to impossible without using the dom.
this is fixed by this PR.
Code extracted from the core text branch.

### CODE REVIEW

**Comment by Dogild** [comment]
Nice, can you add a manual test for this one please ?

**Comment by daboe01** [comment]
@Dogild  https://github.com/cappuccino/cappuccino/pull/2476/commits/85648c7f11d687bb92f06bdbb30b56f719e4248b adds canvas drawn text to Manual/CGCanvasContext

**Comment by daboe01** [comment]
-#needs-unit-test

**Comment by Dogild** [comment]
Thanks !

**Pull request merged**
