### PR TITLE
Update README.markdown

### PR DESCRIPTION
**Pull request by daboe01**
simplifications + add a link to https://cappuccino-cookbook.5apps.com/

### CODE REVIEW

**Comment by mrcarlberg** [comment]
I think it is a good thing to update this readme file. It has a lot of old information and broken links

**Comment by mrcarlberg** [comment]
Is it possible to alter the commit messages so they conform to these rules? https://github.com/cappuccino/cappuccino/blob/master/CONTRIBUTING.md

**Comment by daboe01** [comment]
@mrcarlberg would you accept a new PR with a single commit?

**Comment by mrcarlberg** [comment]
I think I can Squash this pull request to just one commit. I think GitHub will allow me to alter the commit message when doing that. I'll try to do that so we don't need to open a new one.

**Comment by mrcarlberg** [comment]
I'm going to leave this open for a day or so. If someone wants to comment on these changes before we merge.

**Comment by daboe01** [comment]
should we add an advertisement for cappcon liege 2018?

**Comment by mrcarlberg** [comment]
Please do.

**Comment by daboe01** [comment]
done.

**Pull request merged**
