### PR TITLE
NEW: Add first responder management based on content view to CPScrollView

### PR DESCRIPTION
**Pull request by didierkorthoudt**
This will (un)set CPThemeStateFirstResponder on CPScrollView based on the content view.

For now, only CPTableView's can initiate first responder state on a CPScrollView (and only if there's no in-cell editing).

This should be adapted when global focus ring management will be added to Cappuccino.

With this PR, it's easy to add a focus ring around a CPScrollView containing a CPTableView which is the first responder of the window (this will be used by Aristo3).

### CODE REVIEW

**Comment by mrcarlberg** [comment]
@didierkorthoudt Can you please look into why the test case will fail.

CPScrollViewTest.......
addFailure test=[CPScrollViewTest testNotificationsRegistered]: Notications registered for the scrollView in the notification center are wrong expected:<@[
    @"CPScrollerStyleGlobalChangeNotification",
    @"_CPWindowDidChangeFirstResponderNotification"
]> but was:<@[
    @"CPScrollerStyleGlobalChangeNotification"
]>

**Comment by didierkorthoudt** [comment]
@mrcarlberg Well, I've added a new notification listening in order to implement this new functionality. So I guess that the unit test is not adapted. I check immediately. Sorry for this.

**Comment by didierkorthoudt** [comment]
@mrcarlberg Done.

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
