### PR TITLE
fixed: background color attribute was ignored by CPTextView

### PR DESCRIPTION
**Pull request by daboe01**

### CODE REVIEW

**Comment by daboe01** [comment]
+TextView
-#new

**Comment by cacaodev** [comment]
Hi @daboe01 , is there a manual test where we can see this feature ?

**Comment by daboe01** [comment]
@cacaodev there you have it
Bildschirmfoto 2020-05-29 um 21 23 35

**Comment by daboe01** [comment]
-#ready-to-commit

**Comment by daboe01** [comment]
+#ready-to-commit

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
