### PR TITLE
Adding support for the node engine

### PR DESCRIPTION
**Pull request by FrankReh**

### CODE REVIEW

**Comment by mrcarlberg** [comment]
Travis checks has fail due to this pull request needs updated Cappuccino-Base https://github.com/cappuccino/cappuccino-base/pull/6

**Comment by FrankReh** [comment]
Some cleanup commits added.

**Comment by mrcarlberg** [comment]
Frank, thanks for the cleanup of the code.

Next time please make a separate pull request as the cleanup stuff has nothing to do with the support for Node. It will make it easier for us to merge just the cleanup or just the Node support.

We like pull requests that focus on just one thing. 😃 

Keep up the good work!

**Comment by FrankReh** [comment]
Sorry about that but in my defense it's my first time working with pull requests. I pushed my work up yesterday and went to create a new pull request and the github program put me into the first pull request. If there was a choice for me to make, I missed it. Can the original pull request be dropped or undone?

I would prefer separate pull requests too. Maybe the problem was I put my commits into the same branch?  If it lets me, I'll cancel those commits and create a different branch. 

-Frank

**Comment by mrcarlberg** [comment]
Yes, as you said the problem is that you have made the pull request from your master branch. It is often better to create another branch and create the pull request from that. It is not that much of a problem to have your cleanup in this pull request so just leave it if you can't cancel the commits.

**Comment by FrankReh** [comment]
Would you mind if I closed the pull request completely from my cappuccino
repository and created one from a new branch that just had my node changes
and yours cherry-picked to it?

-Frank

**Comment by mrcarlberg** [comment]
That is ok!
Please refer to this pull request from the new one so it is easy to follow. Then you can close this one.

**Comment by FrankReh** [comment]
Closing this pull request.  A new one, meant to be more concise, has been opened in its place.  #2538

**Comment by FrankReh** [comment]
Done.  Should keep things saner, I agree.

**Pull request closed without merging**
