### PR TITLE
Fixed: missing requirements for developers...

### PR DESCRIPTION
**Pull request by daboe01**
... in README.markdown

### CODE REVIEW

**Comment by daboe01** [comment]
-#new
+documentation

**Comment by mrcarlberg** [comment]
We should add information that we need ```gcc``` or ```clang``` to compile Objective-J code from the command line. It is used to preprocess all macros like ```#include```, ```#define``` and ```#if``` etc...

**Comment by daboe01** [comment]
@aparajita will this hold for cappuccino 2 (beeing able to code with only a simple editor?)

**Comment by mrcarlberg** [comment]
We want everything to be javascript so the need for ```gcc``` or ```clang``` will disappear in the future.

We don't know exactly when or how at the moment but this is an important issue.

**Comment by daboe01** [comment]
from a marketing perspective i would like to be minimalistic here.
shouldn't we leave it as in https://github.com/cappuccino/cappuccino/pull/2475/commits/a4d374ecb6aad9ad5a904529090613b14095628d?

**Comment by mrcarlberg** [comment]
Ok, I do agree with you. Please revert!

**Comment by mrcarlberg** [comment]
Thanks!

**Pull request merged**
