### PR TITLE
CPWindow live resize notifications

### PR DESCRIPTION
**Pull request by cacaodev**
Adds CPWindowWillStartLiveResizeNotification
         CPWindowDidEndLiveResizeNotification

Testing added in CPWindowResizeStyle manual test.

### CODE REVIEW

**Comment by daboe01** [comment]
-#new
+AppKit

**Comment by daboe01** [comment]
looks good to me.
@cacaodev is this ready to commit from your side?

**Comment by mrcarlberg** [comment]
Works for me!

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
