### PR TITLE
FIXED: Add Dark Mode to XcodeCapp

### LINKED ISSUE #2787: XcodeCapp Incompatible with Mojave Dark Mode
When compiling under Mojave and Xcode 10.1, almost all text/labels disappear when using dark mode. Probably a text color issue.

### PR DESCRIPTION
**Pull request by brianmpalma**
Fixed: XcodeCapp Incompatible with Mojave Dark Mode

This commit adds dark mode compatibility for XcodeCapp in Mojave and up.

This commit also fixes an issue where two NSBox instances in IB had a borderRadius of 100 (`boxStatus` and `boxImport`). The borderRadius values are now updated to be half the size of the height and width values, restoring the circle visual.

Fixes #2787

### CODE REVIEW

**Comment by enquora** [comment]
This needs to be updated with the deployment target changed from /Applications to ~/Applications (for Catalina compatibility) but it's otherwise ready to go, imo.

Perhaps @daboe01 could kick the tires to confirm?

**Comment by enquora** [comment]
Installation directory for Target -> XcodeCapp is $(LOCAL_APPS_DIR) although for Project -> XcodeCap it is $USER_APPS_DIR — these should both be set to $USER_APPS_DIR.

Recommend incrementing version number, perhaps to 4.5.0

**Comment by mrcarlberg** [comment]
@brianmpalma Can you update this with the suggestions from @enquora?

**Comment by mrcarlberg** [comment]
@didierkorthoudt Do you have any comments on this as you have done some changes to XcodeCapp too?

**Comment by daboe01** [comment]
-#new
+#needs-improvement
+Tools

**Comment by enquora** [comment]
The 'needs-improvement' label on something like this is counter-productive — it is non-descriptive and non-useful to the point of potentially acting as a discouragement to contributors. Where is cappbot configured - I'd like to have a look. Is a log available?

**Comment by daboe01** [comment]
@enquora the needs-improvement is just a formal marker for the question of core-dev @mrcarlberg from 3 days ago

**Comment by enquora** [comment]
Let's merge this now - I'll create a PR immediately after with these minor changes. It will also allow me to finally fix the outstanding copyright window PR. The author has provided good work on this and if he is busy with other things we should get this into master as-is (along with the well-deserved credit).

**Comment by daboe01** [comment]
+#ready-to-commit
-#needs-improvement

**Comment by mrcarlberg** [comment]
Thanks! Merged!

**Comment by mrcarlberg** [comment]
@enquora I have now merged this into the master. Please feel free to create a new pull request with your changes.

**Pull request merged**
