### PR TITLE
fixed: native paste on chrome was not working as robustly as it should [+1]

### PR DESCRIPTION
**Pull request by daboe01**
previously, pasting from mail headlines failed silently.
this is fixed by this PR.

### CODE REVIEW

**Comment by daboe01** [comment]
+bug
+AppKit
+regression
+Chrome
+#ready-to-commit

**Comment by daboe01** [comment]
+1

**Comment by daboe01** [comment]
+bug
+AppKit
+regression
+Chrome
+#ready-to-commit
-#new

**Comment by daboe01** [comment]
+TextView

**Comment by mrcarlberg** [comment]
I really don't know exactly how to test this but I tried to paste some rich text but it failed.

This is the text I copied:
skarmavbild 2016-12-09 kl 13 56 45

This is the result after paste in CPTextView running Chrome:
skarmavbild 2016-12-09 kl 13 57 23

**Comment by daboe01** [comment]
@mrcarlberg from which app did you copy?

**Comment by daboe01** [comment]
@mrcarlberg ok, i see this also with the Notes app. Will fix this asap.

**Comment by daboe01** [comment]
@mrcarlberg fixed. i found a much better solution that works robustly at the end :-) could you please test again?

**Comment by mrcarlberg** [comment]
Great, It now works much better.

I have found one minor "bug" that might have been there before?

I copy this text:
skarmavbild 2016-12-12 kl 12 38 22

Then paste it into this:
skarmavbild 2016-12-12 kl 12 38 22

I get this:
skarmavbild 2016-12-12 kl 12 39 40

When I do undo with cmd-z I get this:
skarmavbild 2016-12-12 kl 12 38 59

The text is correct but the cursor is not positioned at the right place. I don't know if it is related to this? We might want to open a new PL for this?

**Comment by daboe01** [comment]
@mrcarlberg the cursor-issue is unrelated to this PR.
if you agree, i will amend this PR with a fix.

**Comment by mrcarlberg** [comment]
If it is an easy and small fix please do it. If not open a new PR.

**Comment by daboe01** [comment]
@mrcarlberg any more findings ;-)

**Comment by mrcarlberg** [comment]
Merged! Thanks a lot for your work!

**Pull request merged**
