### PR TITLE
Fixed: CPTextField doesn't optimize tracking areas management

### PR DESCRIPTION
**Pull request by didierkorthoudt**
This PR implements : 
- cursor management via cursorUpdate instead of mouseMoved ;
- smart tracking area creation (only when needed) ;
- a fix to previous incorrect behavior when dragging on a disabled text field (previously, text was indeed selected).

### CODE REVIEW

**Comment by didierkorthoudt** [comment]
The fix for the incorrect behavior is not related to tracking areas but when testing my PR, I've found that Cappuccino behaves differently from Cocoa, so I propose this fix.

**Comment by Dogild** [comment]
Hi @didierkorthoudt, can you change the commit message and follow the cappuccino commit guideline please (https://github.com/cappuccino/cappuccino/blob/master/CONTRIBUTING.md) :)

**Comment by didierkorthoudt** [comment]
Hi @Dogild. I've changed the summary (FIXED -> Fixed & added a period) but I don't see what I should change elsewhere... Any clue for me ? Thanks

**Comment by daboe01** [comment]
@didierkorthoudt i think he wants you to change the commit message 'initial commit' to the title of your PR (use git ammend...git push --force)

**Comment by didierkorthoudt** [comment]
@daboe01 Thanks ! I've read carefully the doc but missed this one...  ;-)

**Comment by Dogild** [comment]
Still not correct :)

**Comment by Dogild** [comment]
Thanks

**Pull request merged**
