### PR TITLE
Fixed: underscores missing when accessing CPColor's components ivar

### PR DESCRIPTION
**Pull request by daboe01**
previously, the ivar was erroneously accessed by the property name using dot syntax.
this is corrected by adding the underscore appropriately.
credits: <https://groups.google.com/forum/?fromgroups#!topic/objectivej/DbHN1ffcjO0>

### CODE REVIEW

**Comment by aparajita** [comment]
Danke. You tested it?

**Comment by daboe01** [comment]
no.

maybe michael can test it in his app?

@michael:
you can download the fixed capp framework here:
<https://github.com/daboe01/cappuccino/tree/fix-CGContextDrawRadialGradient>

best greetings,
daniel

**Comment by Dogild** [comment]
More informations here : https://groups.google.com/forum/?fromgroups=#!topic/objectivej/DbHN1ffcjO0

The manual test CPGradientTest looks good with the current version ! This fix will work when using CPColor's array instead of using the method `CGGradientCreateWithColorComponents()` (which is how cocoa works)

**Comment by Dogild** [comment]
According to the Cocoa doc (https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/CGGradient/#//apple_ref/c/func/CGGradientCreateWithColors), when using the gradient color you need to pass CGColor and not CPColor. 

Everything looks good in the framework right now (manual test in CPGradientTest)

**Pull request closed without merging**
