### PR TITLE
Fixed: legacy scrollers used Aristo1 artwork in Aristo2

### PR DESCRIPTION
**Pull request by daboe01**
before this patch, legacy sliders looked odd, after this patch, they look like in the reference images
fixes: #2553

### CODE REVIEW

**Comment by daboe01** [comment]
+#needs-review

**Comment by daboe01** [comment]
this is how legacy scrollers look with this patch:
bildschirmfoto 2017-09-04 um 22 58 53

**Comment by daboe01** [comment]
-#new
+#needs-review

**Comment by daboe01** [comment]
+Theme

**Comment by mrcarlberg** [comment]
When I compare how it looks in Mac OS I feel that here the dark grey scroller is a little wider. It also feels like there is less white margin on both sides of the dark grey scroller.

Is this how it should look?

**Comment by daboe01** [comment]
@mrcarlberg thank you for the feedback!
i just fixed this, and it really looks better :-)
bildschirmfoto 2017-09-27 um 11 05 00

**Comment by daboe01** [comment]
@Dogild may you please review this one?

**Comment by daboe01** [comment]
+#ready-to-commit

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
