### PR TITLE
WORK: CSS Theming CPButton

### PR DESCRIPTION
**Pull request by didierkorthoudt**
This PR adapts the CPButton layoutSubviews method to cope with CSS Theming

### CODE REVIEW

**Comment by didierkorthoudt** [comment]
milestone=1.1

**Comment by jasperdeb** [comment]
I use a checkbox in my CPTableViews

`theColumn = [[CPTableColumn alloc] initWithIdentifier:@"identifier"];`
`[tableViewContractContent  addTableColumn:theColumn];`
`[theColumn setEditable:YES];`
`var checkBoxTemp = [[CPCheckBox alloc] init];`
`[theColumn setDataView:checkBoxTemp];`

The box and the "v" are not sticking together.

image

**Comment by jasperdeb** [comment]
Concerning the animation of the checkbox. This is nice when the box is actually clicked during a mouse event. 
Nevertheless when you use the CPCheckBox as an element in a CPTableView the animation is also there when the data in the CPTableView is (re)loaded. I think the animation should not be there during (re)loading.

**Comment by daboe01** [comment]
-#new
+Theme

**Pull request closed without merging**
