### PR TITLE
Fixed: CPTextView keyboard issue in recent Firefox versions

### LINKED ISSUE #2873: entering hashtag key adds a pound-key in FF70
'#' gives you £#

### PR DESCRIPTION
**Pull request by daboe01**
previously, wrong characters were emitted from keyDown: events in more recent Firefox versions. The reason is that keyCodes do not correspond to characters but rather refer to keys on the keyboard.

The bug is exposed in CPTextView that relies on keyDown: events. CPTextFields are not affected because they are based native input elements.

This patch uses the key property that corresponds to characters and not keys.
Works for me on FireFox, Safari and Chrome.

fixes #2873

### CODE REVIEW

**Comment by daboe01** [comment]
-#new
+FireFox
+AppKit

**Comment by daboe01** [comment]
+#needs-review

**Comment by mrcarlberg** [comment]
Can you please add some comments in the code that describe this behavior. Also why this works better. Some examples in the comments would be fantastic too.

**Comment by daboe01** [comment]
@mrcarlberg done so. is this sufficient?

**Comment by daboe01** [comment]
-#needs-review

**Comment by daboe01** [comment]
@mrcarlberg my userbase of ~100 per day has been testing this for 2 weeks (we are unfortunately a FF shop). no issues have been reported so far.

**Comment by mrcarlberg** [comment]
After looking into this a bit I think this might fix the problem in Firefox but the base problem is that `event.charCode` and `event.keyCode` are deprecated. The fix make sure we use the `key` property when the length is one but most of the logic still use the old properties.

Do you know if `charCode` corresponds the the `code` property all the time?

**Comment by daboe01** [comment]
@mrcarlberg the issue with firefox is that String.fromCharCode(e.charCode) does not always match the key that was pressed, at least not so on a german keyboard.

KeyboardEvent.key is the correct alternative to get the key that was pressed according to https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key 

we already have several other workarounds for weird charCode behaviors scattered around 
 CPPlatformWindow+DOM.j

**Comment by daboe01** [comment]
@mrcarlberg this issue is a real show stopper in Germany. Here, FF-usage is still very prevalent. I therefore suggest to merge this fix sooner than later. IMHO a full rework of CPPlatformWindow+DOM.j to use key instead of charCode should be pursued in a second step.

**Comment by mrcarlberg** [comment]
Yes, a rework of this has to be done in the future. I will merge this.

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
