### PR TITLE
CHANGED: This removes the removeAllTrackingAreas method

### PR DESCRIPTION
**Pull request by didierkorthoudt**
This PR removes the removeAllTrackingAreas utility method as it is « dangerous » to use without very good knowledge of underlying view hierarchy tracking area management. This method :
- remove all tracking areas whatever the owner is ;
- doesn’t exist in Cocoa.

### CODE REVIEW

**Comment by didierkorthoudt** [comment]
This PR needs PR #2681 (CPTextField was using removeAllTrackingAreas before PR #2681)

**Comment by cacaodev** [comment]
Can you remove the failing test, tx.

**Comment by didierkorthoudt** [comment]
The test failure was due to missing #2681. I've committed what is done in this PR. Should be "merge compatible" as I used the same code.

**Comment by didierkorthoudt** [comment]
Sorry, some removeAllTrackingAreas are always there. Please wait

**Comment by didierkorthoudt** [comment]
Closing as this will be treated in PR #2681

**Pull request closed without merging**
