### PR TITLE
Fixed: legacy scrollers were not clickable under some circumstances

### PR DESCRIPTION
**Pull request by daboe01**
previously, clicks on unselected scrollers in legacy mode were ignored under certain circumstances.
this caused combobox menus to "freeze".
this PR ensures that legacy scrollers are always clickable (as they are always visible).

fixes: #2509

### CODE REVIEW

**Comment by daboe01** [comment]
+AppKit
+bug
+#needs-review
+Theme

**Comment by daboe01** [comment]
+AppKit
+bug
+#needs-review
+Theme

**Comment by daboe01** [comment]
-#new

**Comment by mrcarlberg** [comment]
Great! Merged! Thanks

**Pull request merged**
