### PR TITLE
New: The compiler will now create warnings for variables that are never read

### PR DESCRIPTION
**Pull request by mrcarlberg**
I have used this feature for some time at our project and been able to find a few unknown bugs. Now is the time for it to reach a wider audience.

Please try it out and let me know if this is a good warning that should be added to our compiler

This new warning adds a lot of warnings in the Cappuccino frameworks. I have turned off
the warning in the Jakefiles when compiling most of the Cappuccino frameworks. But it is
on as default for any user projects.

So there is also a new feature to turn off/on warnings as a compiler flag.

These flags are (all flags are on as default):
-Wunused-but-set-variable                    Warning when a local variable is never read.
-Wshadow-ivar                                Warning when a local variable is shadowing an instance variable for the class.
-Wcreate-global-inside-function-or-method    Warning when creating a global variable inside a function or method.
-Wunknown-class-or-global                    Warning when a class or global variable is not known.
-Wunknown-ivar-type                          Warning when the type for an instance variable is not known.

To turn off a flag add a 'no-' prefix. Example: -Wno-unused-but-set-variable

For an example how to use it in a Jakefile please look at the Jakefiles in this commit.

### CODE REVIEW

**Comment by mrcarlberg** [comment]
The travis build is failing as it can not handle changes in the compiler.

**Comment by daboe01** [comment]
-#new
+Tools

**Comment by daboe01** [comment]
@mrcarlberg can you please check the CI issue?

**Comment by mrcarlberg** [comment]
@daboe01 The problem is as I wrote above "The travis build is failing as it can not handle changes in the compiler". There are no problems if you run the tests locally.

**Comment by daboe01** [comment]
@mrcarlberg i should have read this. sorry for the inconvenience.

**Comment by mrcarlberg** [comment]
@daboe01 No problems

**Comment by mrcarlberg** [comment]
It should be wonderful if someone could test this pull request on there project and let me know if there are any bugs....

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
