### PR TITLE
WORK: CSS theming windows

### PR DESCRIPTION
**Pull request by didierkorthoudt**

### CODE REVIEW

**Comment by didierkorthoudt** [comment]
milestone=1.1

**Comment by jasperdeb** [comment]
I use sheets, and I show them using the following code

`[CPApp beginSheet:sheet modalForWindow:theMainWindow modalDelegate:self didEndSelector:nil contextInfo:nil]; `

I get the following error in Chrome

image

**Comment by jasperdeb** [comment]
I use a checkbox in my CPTableViews

`theColumn = [[CPTableColumn alloc] initWithIdentifier:@"identifier"];`
`[tableViewContractContent  addTableColumn:theColumn];`
`[theColumn setEditable:YES];`
`var checkBoxTemp = [[CPCheckBox alloc] init];`
`[theColumn setDataView:checkBoxTemp];`

The box and the "v" are not sticking together.

image

**Comment by daboe01** [comment]
-#new
+Theme

**Pull request closed without merging**
