### PR TITLE
New: possibility to draw automatically in high DPI in canvas2D

### LINKED ISSUE #2175: Retina support for canvas2D
When using canvas, we don't support the retina displayed.

The idea is to scale the canvas and context by the ratio of the current display.

My first idea was to change the context before calling the method `drawRect:` of a `CPView`, but this solution raised some issues with the `CPTableView`, `CPPopover` and `CPOutlineView`.

If you want to play and improve the solution, this is the code I have used : 

```obj-j
- (void)displayRectIgnoringOpacity:(CGRect)aRect inContext:(CPGraphicsContext)aGraphicsContext
{
    if ([self isHidden])
        return;

#if PLATFORM(DOM)
    [self lockFocus];

    var aRect = CGRectCreateCopy(aRect),
        context = [[CPGraphicsContext currentContext] graphicsPort],
        devicePixelRatio = window.devicePixelRatio || 1,
        backingStoreRatio = context.webkitBackingStorePixelRatio ||
                        context.mozBackingStorePixelRatio ||
                        context.msBackingStorePixelRatio ||
                        context.oBackingStorePixelRatio ||
                        context.backingStorePixelRatio || 1,
        ratio = devicePixelRatio / backingStoreRatio,
        canvas = self._DOMElement.getElementsByTagName("canvas")[0],
        oldWidth = aRect.size.width,
        oldHeight = aRect.size.height;

    canvas.width = oldWidth * ratio;
    canvas.height = oldHeight * ratio;
    canvas.style.width = oldWidth + 'px';
    canvas.style.height = oldHeight + 'px';

    context.scale(ratio, ratio);

    CGContextClearRect(context, aRect);

    [self drawRect:aRect];
    [self unlockFocus];
#endif
}
```

### PR DESCRIPTION
**Pull request by Dogild**
Previously, Cappuccino didn't handle retina device when drawing for canvas2D. Now it does.
To do that, Cappuccino will firstly calculate the pixel ratio of the current device, then it needs to change the css style of the canvas by multiply it by the current pixel ratio and finally scale the canvas by this pixel ratio.

More information about high DPI drawing here : http://www.html5rocks.com/en/tutorials/canvas/hidpi/

Added the method `setAllowsHighDPIDrawing:` and `allowsHighDPIDrawing` to deactivate or activate this feature.

Fixed #2175

### CODE REVIEW

**Comment by Dogild** [comment]
I just took a look to this feature and it looks like it works actually. There was an issue in mine side and it looks it fixed everything.

I had a ```canvas = self._DOMElement.getElementsByTagName("canvas")[0]``` somewhere, and it transformed things badly...

**Comment by primalmotion** [comment]
we are going to use this PR internally for a while and see if it breaks something.

**Comment by primalmotion** [comment]
Everything runs smoothly for a while.

**Comment by primalmotion** [comment]
+#fixed

Thanks

**Pull request merged**
