### PR TITLE
CPView.j, fix typo: _ephereralSubviews → _ephemeralSubviews. Line #3462 references the correct spelling.

### PR DESCRIPTION
**Pull request by michaelbach**

### CODE REVIEW

**Comment by cacaodev** [comment]
Hi michael, it seems you are pushing unrelated changes on the same branch.
One pr per feature improvement is needed before any reviewing.
Tx

**Comment by michaelbach** [comment]
Thank You! I understand – I obviously cannot handle git well enough yet. So I'll make a new fork, make changes in CPSlider and issue a new pull request after deleting this one.

**Comment by daboe01** [comment]
@michaelbach can you please close this one and reopen the appropriate PRs? IMHO these should make it into the upcoming release.

**Comment by daboe01** [comment]
-#new
+#needa-improvement

**Comment by daboe01** [comment]
+#needs-improvement

**Pull request closed without merging**
