### PR TITLE
Fixed: constructor of CPDate can take string param

### PR DESCRIPTION
**Pull request by Dogild**
Previously, when making a CPDate with some constructors, we could pass a string or nil to create a date. For example it was allowed to do var date = [CPDate dateWithTimeIntervalSince1970:"10"];

Now this is not possible anymore and it works like in Cocoa, only number are authorized.

### CODE REVIEW

**Comment by primalmotion** [comment]
would be cool to put a warning first before going hardcore

**Comment by primalmotion** [comment]
+#needs-improvement

**Comment by Dogild** [comment]
Done !

**Comment by primalmotion** [comment]
+#fixed

Thanks!

**Pull request merged**
