### PR TITLE
CPPasteboad.j removal of dead code

### PR DESCRIPTION
**Pull request by daboe01**
previously, CPPasteboad contained dead code that was left over from refactoring the native pasteboard stuff into the DOM folder

### CODE REVIEW

**Comment by daboe01** [comment]
-#new
+AppKit
+#needs-review

**Comment by cacaodev** [comment]
Do you know why the native pasteboard approach have been obsoleted and if there would be a chance one day to take it back ?

**Comment by daboe01** [comment]
@aljungberg refactored and encapsulated the native pasteboard handling into CPPlatformPasteboard some time ago.

the code that this PR removes is most likely very ancient.
i did not find any reference to cpPasteboardWithName anywhere in the repository (not even in the nativehost)

**Comment by daboe01** [comment]
@aljungberg are you still around?

**Comment by aljungberg** [comment]
Yeah pretty sure this is just old native host related stuff that won't work today.

**Pull request merged**
