### PR TITLE
WORK: Aristo3 Theme

### PR DESCRIPTION
**Pull request by didierkorthoudt**
This PR will be updated as work on Aristo3 Theme will progress.

Please follow https://github.com/cappuccino/cappuccino/wiki/CSS-Theming-&-Aristo-3-:-Work-in-progress

### CODE REVIEW

**Comment by didierkorthoudt** [comment]
milestone=1.1

**Comment by jasperdeb** [comment]
I use a checkbox in my CPTableViews

`theColumn = [[CPTableColumn alloc] initWithIdentifier:@"identifier"];`
`[tableViewContractContent  addTableColumn:theColumn];`
`[theColumn setEditable:YES];`
`var checkBoxTemp = [[CPCheckBox alloc] init];`
`[theColumn setDataView:checkBoxTemp];`

The box and the "v" are not sticking together.

image

**Comment by jasperdeb** [comment]
@didierkorthoudt Checkbox fix seems to work. The check and the box stick together.

Nevertheless, when the first row height of a table is not the same after a refresh of the CPTableView, there is an unwanted animation?
http://bouwcloud.be/capMovies/movingcheckboxInTable.mov

**Comment by daboe01** [comment]
-#new
+Theme

**Pull request closed without merging**
