### PR TITLE
New: first work on AristoFlat

### PR DESCRIPTION
**Pull request by Dogild**
Note: it still needs more (lot) works.

### CODE REVIEW

**Comment by Dogild** [comment]
People who wants to work on that, feel free to ask me to add you on my remote

**Comment by kicsipixel** [comment]
Are you still working on this? Can I help?

**Comment by Dogild** [comment]
Nop, I don't have the time to work on this one, feel free to continue it ;)

**Comment by daboe01** [comment]
+Theme

**Comment by daboe01** [comment]
this one looks more promising:
http://www.segi.be/Aristo3Showcase/index.html

**Comment by Dogild** [comment]
Closing this one since @didierkorthoudt took the lead on something different

**Pull request closed without merging**
