### PR TITLE
WORK: CSS theming CPSearchField

### PR DESCRIPTION
**Pull request by didierkorthoudt**
This PR needs #2777 !

### CODE REVIEW

**Comment by didierkorthoudt** [comment]
milestone=1.1

**Comment by jasperdeb** [comment]
When a CPSearchField is used in an automatic layout, the magnifying glass in the center of textfield does not follow the changed width of the field. In Cocoa the position of the magnifying glass is updated when the size changes.

`[searchField setAutoresizingMask: CPViewWidthSizable];`

**Comment by jasperdeb** [comment]
> When a CPSearchField is used in an automatic layout, the magnifying glass in the center of textfield does not follow the changed width of the field. In Cocoa the position of the magnifying glass is updated when the size changes.
> 
> `[searchField setAutoresizingMask: CPViewWidthSizable];`

Seems to be fixed in the build of 28/04/2019.

**Comment by daboe01** [comment]
-#new
+Theme

**Pull request closed without merging**
