### PR TITLE
fixed: CPButton's images were lost when becoming disabled

### LINKED ISSUE #2977: CPButton setImage: does not set the image in disabled state
@didierkorthoudt 
IMHO can be easily fixed by adding this line to setImage: 
[self setValue:spinnerImg forThemeAttribute:@"image" inState:CPThemeStateDisabled];
should i make a PR with this?
am i missing something?

### PR DESCRIPTION
**Pull request by daboe01**
fixes #2977

### CODE REVIEW

**Comment by daboe01** [comment]
+theme

**Comment by daboe01** [comment]
-#new

**Comment by didierkorthoudt** [comment]
Well, I have to look but your proposed fix disables setting another image when the button is disabled…

**Comment by didierkorthoudt** [comment]
Well, your proposed fix is the best solution.
In Cocoa, there's no specific mean to set a specific image for the disabled state.
This could always been achieved programmatically even with your fix.
So, OK for me.

**Comment by daboe01** [comment]
+#ready-to-commit

**Comment by mrcarlberg** [comment]
I agree that this is the best solution as mentioned, there's no specific mean to set a specific image for the disabled state in Cocoa.

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
