### PR TITLE
CPTableView: fix invisible dragged rows

### LINKED ISSUE #2549: Issue Drag row in CPTableView
Hi,

I have experienced something I assume is a bug in the framework. When I create a CPTableView, and implement the drag and drop delegates, there is some strange behaviour.

When I drag one of the lines which is initially visible to the drop locations, I visually see the dragged table row moving along with my mouse. 
If I select a row somewhat lower (and only visible when scrolled down), the drag and drop feature works as it should, but visually does not show the dragged line when moving arround with the mouse.

Tested this also for the CPOutlineView, same problem over there.

image

I have looked in the issues, but have not found a similar report.

Thanks for the feedback.

### PR DESCRIPTION
**Pull request by cacaodev**
Fixes #2549 

@jasperdeb Can you confirm this works for you ?

### CODE REVIEW

**Comment by mrcarlberg** [comment]
@jasperdeb Can you please confirm this works for you as we want to merge this fix to the master branch?

**Comment by jasperdeb** [comment]
I will check as soon as possible. 
My first time to test a bugfix, so still looking how to do this.

**Comment by cacaodev** [comment]
@jasperdeb If you ask on gitter, you should get a quick answer.
https://gitter.im/cappuccino/cappuccino

**Comment by mrcarlberg** [comment]
@jasperdeb From command line you need to get the new fixed version of Cappuccino. Then you need to build it. 
```
git clone https://github.com/cacaodev/cappuccino.git
cd cappuccino
git checkout cptableview-issue#2549
jake clobber
jake install
```

You might need to copy the newly built framework to your project if you are not using soft links.

```
cd <your-project>
capp gen -f
```

**Comment by jasperdeb** [comment]
Thank you.

I will test later today.

**Comment by jasperdeb** [comment]
Despite this fix, for me it still does not seem to work in my application.

I have attached a screenshot. First the rows up to nr 32 are visible in the view after the initial loading of my view. Row 38 is only partially visible while dragging (see screenshot attached). Starting from the row below ID 38 no rows are visible while dragging. 

firstrowerror

Tested on Mac OS Chrome 60 and Safari 10.1.1.

**Comment by cacaodev** [comment]
It works for me in the manual tests: TableTest/DragAndDrop for cell based tables and TableTest/ViewBasedCib for view-based tables.
Does it for you ?

**Comment by jasperdeb** [comment]
Mistake was on my side. JDK was not installed, therefore compilation was not successfull.

Now I have managed to compile the source code, and I confirm that the bug fix works just fine.

Thx.

**Comment by daboe01** [comment]
+#works-for-me

**Pull request merged**
