### PR TITLE
fixed: network errors had been silently ignored by CPURLConnection

### PR DESCRIPTION
**Pull request by daboe01**
see discussion in https://stackoverflow.com/questions/28556398/how-to-catch-neterr-connection-refused

### CODE REVIEW

**Comment by daboe01** [comment]
In commit 09b8db8 i want to verify, whether a delegate method has been triggered by an asynchronous process. how can i test asynchronous behavior using OJTest?

**Comment by daboe01** [comment]
-#new
+Foundation
+#needs-review

**Comment by daboe01** [comment]
@mrcarlberg can the asynchronous unit test be fixed with your latest extensions to the objective-j language?

**Comment by mrcarlberg** [comment]
Yes, you can use async test cases with the Node version. Check CPViewControllerTest.j and CPBundleTest.j

**Comment by daboe01** [comment]
i had a brief look at this, and unfortunately this seems to depend on refactoring [CPURLConnection connectionWithRequest:delegate:] to return a Promise? Is this correct?

**Comment by daboe01** [comment]
https://stackoverflow.com/questions/38533580/nodejs-how-to-promisify-http-request-reject-got-called-two-times

**Comment by daboe01** [comment]
@mrcarlberg are you ok with removing the automated test from this PR?
it looks like we can only test this in a later cappuccino version with some refactoring of CPConnection.

**Comment by cacaodev** [comment]
This is very helpful but we need to know the browser support before commiting.

**Comment by daboe01** [comment]
-#needs-review

**Comment by daboe01** [comment]
i will close this one and make a new PR against the node version.
+#wont-fix

**Pull request closed without merging**
