### PR TITLE
Fixed: warnings when compiling cappuccino

### PR DESCRIPTION
**Pull request by Dogild**
Previously, some warnings were raised when compiling Cappuccino.

### CODE REVIEW

**Comment by Dogild** [comment]
I don't have the warnings when compiling on my machine. I need to check on travis !

**Comment by Dogild** [comment]
Looks good !

**Comment by ahankinson** [comment]
Looks good to me too.

-#new
+Tools
+bug
+#ready-to-commit

**Comment by ahankinson** [comment]
milestone=0.9.8

**Comment by primalmotion** [comment]
+#fixed

**Pull request merged**
