### PR TITLE
WORK: CSS theming CPBox

### PR DESCRIPTION
**Pull request by didierkorthoudt**

### CODE REVIEW

**Comment by didierkorthoudt** [comment]
milestone=1.1

**Comment by jasperdeb** [comment]
I set the background of the CPBox to white with the method:

`[box setFillColor:[CPColor whiteColor]]`

This does not seem to work with Aristo3.

**Comment by jasperdeb** [comment]
I set the border type of the CPBox to "CPLineBorder" with the method

`[box setBorderType:CPLineBorder];`

This does not seem to work with Aristo3

**Comment by jasperdeb** [comment]
> I set the background of the CPBox to white with the method:
> 
> `[box setFillColor:[CPColor whiteColor]]`
> 
> This does not seem to work with Aristo3.

`[textBoxsetFillColor:[CPColor colorWithCSSString:"255,255,255"]];` 

does not seem to work as well.

**Comment by daboe01** [comment]
-#new
+Theme

**Pull request closed without merging**
