### PR TITLE
FIXED: Before this PR, when dragging a selected column, selection color remained in place (visual artefact)

### PR DESCRIPTION
**Pull request by didierkorthoudt**
Say you have a table with a selected column, like : 

bug1

If you start dragging this column, the selection color remains on the freed space : 

bug2

This is because, when creating the dragged view (or ghost view), the "will be dragged" column was indeed unselected but without any refresh of the display.

This PR fixes this by simply adding a setNeedsDisplay:YES.

### CODE REVIEW

**Comment by cacaodev** [comment]
Since this method is supposed to just construct the drag view, it would be better to have the display call in the parent method CPTableHeaderView- (void)_startDraggingTableColumn:(CPInteger)aColumnIndex at:(CGPoint)aPoint.

**Comment by didierkorthoudt** [comment]
Well, strictly considering OOP, CPTableHeaderView asks CPTableView to construct the drag view, so it's CPTableView responsibility to take all necessary actions to provide the drag view. Also, CPTableView knows what to do and if / when it has to be refreshed. The drag view could be constructed in another completely different way not needing the CPTableView to be refreshed. So code isolation / abstraction also conducts to leave the setNeedsDisplay in the construction method.

Do you agree with that @cacaodev  ?

**Comment by cacaodev** [comment]
I totally agree.

**Comment by didierkorthoudt** [comment]
OK, so I leave like this ?

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
