### PR TITLE
Fixed: text-sizing by canvas and via DOM sizing differed by 1px

### PR DESCRIPTION
**Pull request by daboe01**
previously, text was wrapped sometimes because the sizing from CPStringDrawing.j differed from the internal sizing of the DOM by 1px in some circumstances. This caused wrapping e.g. in segmented controls. See also https://github.com/cappuccino/cappuccino/issues/1506

This PR fixes the issue by adding 1px to the CPStringDrawing.j  textsizing.
This approach has also been taken in the predecessor implementation of textsizing (https://github.com/cappuccino/cappuccino/commit/48276f989fe1a3f6f6f66cb4cfdda35bd295f318)

### CODE REVIEW

**Comment by cacaodev** [comment]
Naive questions:
1) Are you able to reproduce this bug in the browser with pure javascript/html code ?
2) Do you see a difference when comparing the result in different browsers ?
3) What happens when you CEIL the value, does it solve the problem ?

**Comment by daboe01** [comment]
@cacaodev you are 100% right. This fix is flawed as i am having issues with the CPTextView now. Will definitely try CEIL this weekend and report back.

**Comment by daboe01** [comment]
@cacaodev  ad 3): CEIL indeed solves the prob better than adding 1px.

**Comment by daboe01** [comment]
@cacaodev ad 2): CEIL gives same result in FF, Chrome and Safari

**Comment by daboe01** [comment]
the ceil solution does not seem to have issues with CPTextView

**Comment by cacaodev** [comment]
This will be merged soon but I would feel more comfortable with a manual test that shows the bug & the fix so we can see the result in various browsers. And a pure JS reduction in the same test to check when / if this is fixed in the browser engine.

**Comment by daboe01** [comment]
you can see the issue in the segmented control manual test (the segments wrap without this fix).
the pure JS reduction is here: http://jsfiddle.net/hzyw6b4f/1/

see also: http://stackoverflow.com/questions/4308989/are-the-decimal-places-in-a-css-width-respected

**Comment by Dogild** [comment]
@cacaodev there is no point to keep `_sizeWithFont`, it will just confused future developer and user to have a private method who is only showing an issue in the framework ;)

**Comment by daboe01** [comment]
@dogild do you propose to revert to the traditional DOM only sizing (+1px) and moving the canvas sizing to the typesetter?
this would abrogate the enormous speed gain from the current canvas-based sizing method.

**Comment by daboe01** [comment]
@Dogild _sizeWithFont is needed to prevent ceiling in CPTextView. Ceiling in CPTextView would e.g. break ligatures. Ceiling is needed, however, whenever we need to calculate DOM space.

**Comment by daboe01** [comment]
+TextView

**Comment by mrcarlberg** [comment]
@Dogild @cacaodev Have you got the answers you need for this or should @daboe01 provide more information?

**Comment by cacaodev** [comment]
If the problem is in the width calculation, is it with the canvas method or with the "DOMMetricsElements" method ? And can we fix it there, meaning at a lower level than what this PR does ?

**Comment by daboe01** [comment]
this is my understanding:
1. the width calculation from canvas is ok.
2. the problem arises when floats (aka sub-pixels) are assigned to the DOM css width propery.
3. the floats are effectively ceiled so that the text needs more space than advertised. You can see this here: http://jsfiddle.net/hzyw6b4f/1/

**Comment by cacaodev** [comment]
Tx. To be honest I don't really get the relation between the "fractional width ceiled in elements" exposed in the jsfiddle and our problem but I had only a quick look. My question remains: can we fix that in CPPlatformString + (CGSize)sizeOfString:(CPString)aString withFont:(CPFont)aFont forWidth:(float)aWidth and only for browsers affected.

**Comment by daboe01** [comment]
IMHO, we cannot fix this transparently in + (CGSize)sizeOfString:(CPString)aString withFont:(CPFont)aFont forWidth:(float)aWidth
This is because the higher accuracy from the canvas method is badly needed in CPTypesetter and at the same time breaks the DOM sizing prediction (as exposed in the fiddle).
This PR adds a private high-accuracy API for CPTypesetter and makes the public API behave as before the CPTextView merge.
I see identical results in chrome, safari and FF.

**Comment by cacaodev** [comment]
I don't fully understand the problem here and the relation with ceiling exposed in http://jsfiddle.net/hzyw6b4f/1/ but I don't want to block this PR and the result clearly fixes the bug.
@daboe01  @mrcarlberg if you are ok with this, let's merge it.

**Comment by daboe01** [comment]
+#ready-to-commit
-#needs-improvement

**Comment by daboe01** [comment]
@mrcarlberg IMHO it is time to merge. this is an improvement over the current situation and even over the situation before the CPTextView merge (we did stupidly always add 1px back then)

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
