### PR TITLE
Fixed: smart copy/paste did not work properly [+1]

### PR DESCRIPTION
**Pull request by daboe01**
previously, the smartness of copy/paste was derived from the last click-count.
this behavior is incorrect: the smartness should be based on the click-count of the original copy/cut event.
this error is fixed by this PR, that introduces a private pboard-type for this purpose (so does apple)

### CODE REVIEW

**Comment by daboe01** [comment]
+#ready-to-commit

**Comment by daboe01** [comment]
-#new

**Comment by daboe01** [comment]
+1

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
