### PR TITLE
Native css shadows [+1]

### PR DESCRIPTION
**Pull request by cacaodev**
This PR enables css shadows for all CPWindow subclasses (including panels and menus) when the browser supports the ‘box-shadow ‘ and the ‘border’ css properties. If not, the legacy image-based shadow is used.

The CPNativeShadowFeature have been added to CPCompatibility list of features.

The private class CPWindowView has some new theme attributes:
@"border-top-radius":
@"border-bottom-radius"
@"box-shadow-color":
@"box-shadow-x-offset"
@"box-shadow-y-offset"
@"box-shadow-blur"
@"box-shadow-spread"

These theme attributes can only be modified in theme descriptors. 
Changing their values dynamically in code is not supported.

With Manual Test CPWindowShadowTest

### CODE REVIEW

**Comment by cacaodev** [comment]
shadows-compare

Currently (left), the window border is part of the image-based shadow.
On the right image, with css shadow, the border is from the unmodified bezel-color and is lighter.
Having a darker border would necessitate to modify the themed resources.

**Comment by andresclari** [comment]
Can this be merged?

**Comment by daboe01** [comment]
+1

**Comment by daboe01** [comment]
+Theme

**Comment by cacaodev** [comment]
We need a new artwork for CPWindow bezel-color that includes the border (key and non key).

Previously, the window border was part of the shadow image (see picture above).

I'm not an expert on this.

**Comment by andresclari** [comment]
I have no idea how to regenerate the assets, does it happen on a full build or does it have to be done manually before? Otherwise I could give it a shot.

Does anyone have the steps to follow for that?

**Comment by cacaodev** [comment]
Aristo2 images are there: AppKit/Themes/Aristo2/Resources/window-bezel*
When you build, you will have to jake clean & jake clobber to see the modifications.

**Comment by daboe01** [comment]
@cacaodev @didierkorthoudt do we still need this in the advent of aristo3?

**Comment by cacaodev** [comment]
This PR needs to be adapted in order to fit into Aristo3 css theme. I suggest that we keep it open as a reference for this future work.
Note that this PR supports Aristo 2 and also browsers that do not support css shadows.
When we switch to Aristo 3, we just need to keep this in mind.

**Comment by didierkorthoudt** [comment]
This could be addressed via #2927 …

**Comment by daboe01** [comment]
closing this as we will proceed with Aristo3 anyway.

**Pull request closed without merging**
