### PR TITLE
fixed: pressing capslock inserted whitespaces under certain conditions

### PR DESCRIPTION
**Pull request by daboe01**
the original implementation of CPPlatformWindow+DOM.j was faulty in two ways: firstly, _capsLockActive was accidentally a global variable, secondly, pressing capslock accidentally emitted keyDown:(CPEvent)events

both issues are fixed in this PR

### CODE REVIEW

**Comment by daboe01** [comment]
-#new
+AppKit
+#needs-review
+TextView

**Comment by cacaodev** [comment]
Can you remove the leading underscore like the other class variables.

**Comment by mrcarlberg** [comment]
@daboe01 ```_ capsLockActive``` is an instance variable and not a global variable. Do we need to change that?

**Comment by daboe01** [comment]
@mrcarlberg _capsLockActive used to be a global variable. my PR turns this into a class variable of name capsLockActive (not an instance variable). this makes sense to me, because we can only have one caps-lock state at a time.

**Comment by mrcarlberg** [comment]
@daboe01 I think ```_capsLockActive``` is declared as an instance variable on line 72 in the file```Platform/CPPlatform.j```. ```Platform/DOM/CPPlatformWindow+DOM.j``` is just a category for the class.

**Comment by daboe01** [comment]
@mrcarlberg thank you for spotting this. i adjusted the fix to leave the ivar alone and just fix the actual issue.

**Comment by mrcarlberg** [comment]
@daboe01 I looked into this again and what do you think of solving this in another way?
A press on the caps lock key should result in a flagsChanged event.
I have also included the caps lock state in the modifierFlags. I believe this is how Cocoa works.

**Comment by mrcarlberg** [comment]
Please check my commit above

**Comment by daboe01** [comment]
@mrcarlberg looks like your approach also fixes the issue. good job!

**Comment by daboe01** [comment]
-#needs-improvement
-#needs-review
+#ready-to-commit

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Pull request merged**
