### PR TITLE
fixed: setMinSize: had no effect in platform windows

### LINKED ISSUE #101: CPWindow setMinSize does not set overflow properly [+1]
CPWindow includes utilities to setMinSize and setMaxSize. While these seem to work correctly, when the user resizes the window to less than it&rsquo;s minimum size, the overflow of the window/contentView should be changes to add browser scroll bars into the window.

[original LH ticket](http://cappuccino.lighthouseapp.com/projects/16499/tickets/76)

 This ticket has 0 attachment(s).

### PR DESCRIPTION
**Pull request by daboe01**
previously, platform windows were clipped, even when the were resized below the minSize.
this PR makes platform windows show native scroll-bars as suggested by #583.

fixes #101

### CODE REVIEW

**Comment by daboe01** [comment]
-#new
+#needs-review
+AppKit
milestone=1.0

**Comment by daboe01** [comment]
i just realized that this PR has some issues.
mouse clicks are off, when the body is scrolled natively.
+#needs-improvement

**Comment by daboe01** [comment]
now it works in my testing.
-#needs-improvement

**Comment by mrcarlberg** [comment]
Merged! Thanks!

**Comment by daboe01** [comment]
under super rare circumstances, theWindow._minSize.height seems to become off-by-one due to rounding issues. this causes a native scroll bar to appear only to scroll for a single pixel. not a big issue for me, but worth mentioning here.

**Pull request merged**
