### PR TITLE
NEW: This PR introduces the ability to follow host OS UX-UI

### PR DESCRIPTION
**Pull request by didierkorthoudt**
Please refer to the wiki page : 
[https://github.com/cappuccino/cappuccino/wiki/Following-host-OS-UX-UI](https://github.com/cappuccino/cappuccino/wiki/Following-host-OS-UX-UI)

### CODE REVIEW

**Comment by mrcarlberg** [comment]
This looks really good!

One question, why is the variable `CPApplicationSelectedOSBehavior` and `CPApplicationShouldMimicWindows` global variables? Is it not better if they are something that is managed by set and get class methods on CPApplication?

**Comment by didierkorthoudt** [comment]
Well, in a first implementation, that was the case but as they may be heavily used in low level rendering methods, I thought it would be better to use global variables, like CPApp for example.

But indeed, this could introduce sides effects if the global variables are directly modified without using the ```setOSBehavior``` method.

What do you prefer ? We leave like this or I add getters and setters and keep the variables private ?

**Comment by mrcarlberg** [comment]
It is much better to have getter and setter for a private variable as you say there might be side effects if you set the global variable directly.

**Comment by didierkorthoudt** [comment]
OK, I'll adapt this.

**Comment by didierkorthoudt** [comment]
I've followed @mrcarlberg suggestion to remove usage of global variables.
Aristo2 retro-compatibility is also better handled.
The wiki page will be adapted to reflect new behavior.

**Comment by didierkorthoudt** [comment]
Wiki page adapted.

**Comment by daboe01** [comment]
-#new
+Theme

**Comment by daboe01** [comment]
moved to #3038
+#duplicate

**Pull request closed without merging**
