### PR TITLE
New: CPArray -arrayByApplyingBlock:

### PR DESCRIPTION
**Pull request by cacaodev**
This new method maps the receiver using the provided function.
Similar to javascript or swift map function.

There are tens of places in the fmw where using this method can reduce the amount of code.

With test.

### CODE REVIEW

**Comment by cacaodev** [comment]
It appears that Array.map is a lot slower than for loops. An example here : https://jsperf.com/map-vs-native-for-loop/7

As a consequence, I will remove the native map but I still believe cappuccino needs a map API because it is very common in most languages.
The naming could also be better.
What about ```-arrayByApplyingBlock:``` ? More consistent with other CPArray methods naming and express better the fact that it is an immutable method. And the array prefix tells clearly what it returns.
Of course, in js Block should be Function but we already use Block for other array methods that take a function arg.
What do you think ?

**Comment by aparajita** [comment]
I agree with -arrayByApplyingBlock: as the name.

**Comment by aljungberg** [comment]
I agree, `arrayByApplyingBlock` is more consistent. Methods that return something tend to be named by what they return, like `arrayByAddingObject`.

(Often we say `UsingBlock` -- `arrayByUsingBlock` doesn't sound as clear though. I like your naming, `arrayByApplyingBlock`, better.)

+#needs-improvement

**Comment by aparajita** [comment]
Merci!

**Comment by cacaodev** [comment]
Merged, thanks for your input.

**Pull request merged**
